---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app2-uat
  description: Microservice - app2 for uat environment
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'entity-id=app2-uat'
    backstage.io/kubernetes-namespace: default
    argocd/app-name: app2
  links:
    - url: https://github.com/brunokino/microservice-bootstrap/tree/main/apps/uat/app2
      title: Repo URL
      icon: github
spec:
  owner: guests
  lifecycle: experimental
  type: service
  system: app2-uat
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: app2-uat
  description: Microservice - app2 for uat environment
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/brunokino/microservice-bootstrap/tree/main/apps/uat/app2s
      title: GitOps repo 
      icon: github
spec:
  owner: guests
  lifecycle: experimental
  type: service