---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app1-uat
  description: Microservice - app1 for uat environment
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'entity-id=app1-uat'
    backstage.io/kubernetes-namespace: default
    argocd/app-name: app1
  links:
    - url: https://github.com/brunokino/microservice-bootstrap/tree/main/apps/uat/app1
      title: Repo URL
      icon: github
spec:
  owner: guests
  lifecycle: experimental
  type: service
  system: app1-uat
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: app1-uat
  description: Microservice - app1 for uat environment
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/brunokino/microservice-bootstrap/tree/main/apps/uat/app1s
      title: GitOps repo 
      icon: github
spec:
  owner: guests
  lifecycle: experimental
  type: service