---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app3-uat
  description: Microservice - app3 for uat environment
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'entity-id=app3-uat'
    backstage.io/kubernetes-namespace: default
    argocd/app-name: app3
  links:
    - url: https://github.com/brunokino/microservice-bootstrap/tree/main/apps/uat/app3
      title: Repo URL
      icon: github
spec:
  owner: guests
  lifecycle: experimental
  type: service
  system: app3-uat
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: app3-uat
  description: Microservice - app3 for uat environment
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/brunokino/microservice-bootstrap/tree/main/apps/uat/app3s
      title: GitOps repo 
      icon: github
spec:
  owner: guests
  lifecycle: experimental
  type: service