nginx:
  replicaCount: 2
  service:
    type: LoadBalancer
    port: 80
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: kinoshita.com
        paths:
          - /
