apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bootstrap-uat-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/brunokino/microservice-bootstrap'
        revision: HEAD
        directories:
          - path: 'apps/uat/*'
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    spec:
      project: default
      source:
        repoURL: 'https://github.com/brunokino/microservice-bootstrap'
        targetRevision: HEAD
        path: '{{path}}/chart'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
